# This script parses the section size table generated by "objdump -h". It reads
# two such files and prints the difference in their section sizes.

import sys

filename1 = sys.argv[1]
filename2 = sys.argv[2]


def parse_file(filename):
    lines = open(filename).readlines()
    rv = {}

    for l in lines:
        if len(l) > 4 and l[4] != '.':
            continue
        toks = l.split()
        if len(toks) < 3:
            continue
        name = toks[1]
        size = int(toks[2], 16)
        rv[name] = size
#        print "%6d %s" % (size, name)

    return rv


sizes1 = parse_file(filename1)
sizes2 = parse_file(filename2)

total_diff = 0
for k,v in sizes1.items():
    size2 = sizes2[k]
    diff = v - size2
    print "%6d %s" % (diff, k)
    total_diff += diff

print "Total diff:", total_diff
